Update to DEV dependencies
vitormattos/blueprint-sdk-maker pull request #11
Opened 2019-10-07 09:51 UTC by hyperized

Resolving `dev` part of: https://github.com/vitormattos/blueprint-sdk-maker/issues/8

This PR contains:
- Updated `.travis.yml` file, supporting 7.2, 7.3 and soft fail 7.4.
- Upgrade PHP-unit to 8.x
- Replace `satooshi/php-coveralls` with `php-coveralls/php-coveralls`

If wanted, I can also push some overall code improvements in the SDK.

2019-10-07 14:05 UTC, hyperized commented
Tests are failing because the direct `dev-master` dependency on `itormattos/oasis-mson-parser` seems to trigger the Github API token requirement.

2019-10-08 16:09 UTC, vitormattos reviewed
Look https://travis-ci.org/vitormattos/blueprint-sdk-maker/jobs/594528047

The minimum PHP version is 7.2

I solved the problem with `oasis-mson-parser` package

2020-10-13 22:03 UTC, rafaelneris approved these changes

2020-10-13 22:05 UTC, rafaelneris requested changes
@hyperized Check the Travis CI pipeline.

2020-10-13 22:22 UTC, vitormattos commented
@rafaelneris I believe that the repository of origin of this PR was deleted. I will accept it. Do you want to do the PR to correct the IC?

2020-10-13 22:23 UTC, merged

2020-10-14 12:23 UTC, rafaelneris commented
@vitormattos Sure, I will do this.